Clean up npm package

diff --git a/package/npm/binaries/elm-format b/package/npm/binaries/elm-format
--- a/package/npm/binaries/elm-format
+++ b/package/npm/binaries/elm-format
@@ -1,1 +1,5 @@
-echo "The npm installation of elm-format did not complete successfully! Please try reinstalling elm-format through npm. If you still see this message even after reinstalling, please file a bug at https://github.com/avh4/elm-format/issues to let us know. You can find manual installers at https://github.com/avh4/elm-format"
+#!/bin/sh
+
+echo "ERROR: The npm installation of elm-format did not complete successfully! Please try reinstalling elm-format through npm. If you still see this message even after reinstalling, please file a bug at https://github.com/avh4/elm-format/issues to let us know. You can find manual installers at https://github.com/avh4/elm-format#installation-"
+
+exit 1
